// DO NOT EDIT THIS FILE! IT IS GENERATED.
 namespace LunaScriptEXT.src.Client 
{

	 using System.ComponentModel.Composition;
	 using Microsoft.VisualStudio.Text.Classification; 
	 using Microsoft.VisualStudio.Utilities;

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "void")]
    [Name("void")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class VoidType : ClassificationFormatDefinition
    {
        public VoidType()
        {
            DisplayName = "void";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "int8")]
    [Name("int8")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class Int8Type : ClassificationFormatDefinition
    {
        public Int8Type()
        {
            DisplayName = "int8";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "int16")]
    [Name("int16")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class Int16Type : ClassificationFormatDefinition
    {
        public Int16Type()
        {
            DisplayName = "int16";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "int32")]
    [Name("int32")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class Int32Type : ClassificationFormatDefinition
    {
        public Int32Type()
        {
            DisplayName = "int32";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "int64")]
    [Name("int64")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class Int64Type : ClassificationFormatDefinition
    {
        public Int64Type()
        {
            DisplayName = "int64";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "uint8")]
    [Name("uint8")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class Uint8Type : ClassificationFormatDefinition
    {
        public Uint8Type()
        {
            DisplayName = "uint8";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "uint16")]
    [Name("uint16")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class Uint16Type : ClassificationFormatDefinition
    {
        public Uint16Type()
        {
            DisplayName = "uint16";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "uint32")]
    [Name("uint32")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class Uint32Type : ClassificationFormatDefinition
    {
        public Uint32Type()
        {
            DisplayName = "uint32";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "uint64")]
    [Name("uint64")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class Uint64Type : ClassificationFormatDefinition
    {
        public Uint64Type()
        {
            DisplayName = "uint64";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "float32")]
    [Name("float32")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class Float32Type : ClassificationFormatDefinition
    {
        public Float32Type()
        {
            DisplayName = "float32";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "float64")]
    [Name("float64")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class Float64Type : ClassificationFormatDefinition
    {
        public Float64Type()
        {
            DisplayName = "float64";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "func")]
    [Name("func")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class FuncType : ClassificationFormatDefinition
    {
        public FuncType()
        {
            DisplayName = "func";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "public")]
    [Name("public")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class PublicType : ClassificationFormatDefinition
    {
        public PublicType()
        {
            DisplayName = "public";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "ret")]
    [Name("ret")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class RetType : ClassificationFormatDefinition
    {
        public RetType()
        {
            DisplayName = "ret";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "and")]
    [Name("and")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class AndType : ClassificationFormatDefinition
    {
        public AndType()
        {
            DisplayName = "and";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "or")]
    [Name("or")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class OrType : ClassificationFormatDefinition
    {
        public OrType()
        {
            DisplayName = "or";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "mod")]
    [Name("mod")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class ModType : ClassificationFormatDefinition
    {
        public ModType()
        {
            DisplayName = "mod";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "xor")]
    [Name("xor")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class XorType : ClassificationFormatDefinition
    {
        public XorType()
        {
            DisplayName = "xor";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "global")]
    [Name("global")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class GlobalType : ClassificationFormatDefinition
    {
        public GlobalType()
        {
            DisplayName = "global";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "import")]
    [Name("import")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class ImportType : ClassificationFormatDefinition
    {
        public ImportType()
        {
            DisplayName = "import";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "module")]
    [Name("module")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class ModuleType : ClassificationFormatDefinition
    {
        public ModuleType()
        {
            DisplayName = "module";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeKeywordColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "{")]
    [Name("{")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class LSquigglyType : ClassificationFormatDefinition
    {
        public LSquigglyType()
        {
            DisplayName = "{";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeSymbolColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "}")]
    [Name("}")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class RSquigglyType : ClassificationFormatDefinition
    {
        public RSquigglyType()
        {
            DisplayName = "}";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeSymbolColor();
        }
    }

﻿    [Export(typeof(EditorFormatDefinition))]
    [ClassificationType(ClassificationTypeNames = "->")]
    [Name("->")]
    [UserVisible(false)]
    [Order(Before = Priority.Default)]
    internal sealed class SuperType : ClassificationFormatDefinition
    {
        public SuperType()
        {
            DisplayName = "->";
            ForegroundColor = LunaScript.Share.Constants.GetCurrentThemeSymbolColor();
        }
    }
}
