set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_CXX_EXTENSIONS O)

set_property ( TARGET libos PROPERTY IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/libs/binarys/libos.so )

if(${STATIC_BUILD})
    add_library ( liblunascript SHARED ${compiler_source} )
else()
    add_library ( liblunascript SHARED ${compiler_source} )
endif()
target_include_directories (liblunascript PRIVATE  ${PROJECT_SOURCE_DIR}/libs/include STATIC )
target_include_directories ( liblunascript PRIVATE ${PROJECT_SOURCE_DIR}/src/share/rapidjson/include STATIC )
target_include_directories (liblunascript PRIVATE  ${PROJECT_SOURCE_DIR}/src/share STATIC )
target_compile_options ( liblunascript PRIVATE -Wall -Wextra -Werror )
if ( ${DEBUG_MODE} )
    if ( CMAKE_CXX_COMPILER_ID STREQUAL "GNU" )
        target_compile_options ( liblunascript PRIVATE -static-libgcc -static-libstdc++ -g3 -O0 )
    else ()
        target_compile_options ( liblunascript PRIVATE -g3 -O0 )
    endif ()
else ()
    if ( CMAKE_CXX_COMPILER_ID STREQUAL "GNU" )
        target_compile_options ( liblunascript PRIVATE -static-libgcc -static-libstdc++ -g3 -O0 )
    else ()
        target_compile_options ( liblunascript PRIVATE -g3 -O0 )
    endif ()
endif ()